name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions
      - 'homework*'
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_GTEST=ON
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: ./allocator_demo-0.0.${{ github.run_number }}-Linux.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}